export enum LogAction {
    ADDED_USER_TO_DUNGEON_BOOST = 'ADDED_USER_TO_BOOST',
    CANCELLED_DUNGEON_BOOST = 'CANCELLED_DUNGEON_BOOST',
    COLLECTED_DUNGEON_BOOST = 'COLLECTED_DUNGEON_BOOST',
    COMPLETED_DUNGEON_BOOST = 'COMPLETED_DUNGEON_BOOST',
    DEPLETED_DUNGEON_BOOST = 'DEPLETED_DUNGEON_BOOST',
    CREATED_DUNGEON_BOOST = 'CREATED_DUNGEON_BOOST',
    DOWNGRADED_DUNGEON_BOOST = 'DOWNGRADED_DUNGEON_BOOST',
    REMOVED_USER_FROM_DUNGEON_BOOST = 'REMOVED_USER_FROM_DUNGEON_BOOST',
    SIGNED_TO_DUNGEON_BOOST = 'SIGNED_TO_DUNGEON_BOOST',
    UN_SIGNED_TO_DUNGEON_BOOST = 'UN_SIGNED_TO_DUNGEON_BOOST',
    SIGNED_FOR_TEAM_TAKE = 'SIGNED_FOR_TEAM_TAKE'
}