export enum Stacks {
  'Any' = 'Any',
  'Cloth' = 'Cloth',
  'Leather' = 'Leather',
  'Mail' = 'Mail',
  'Plate' = 'Plate',
  'Mage' = 'Mage',
  'Priest' = 'Priest',
  'Warlock' = 'Warlock',
  'Demon Hunter' = 'Demon Hunter',
  'Druid' = 'Druid',
  'Monk' = 'Monk',
  'Rogue' = 'Rogue',
  'Hunter' = 'Hunter',
  'Shaman' = 'Shaman',
  'Death Knight' = 'Death Knight',
  'Paladin' = 'Paladin',
  'Warrior' = 'Warrior',
}
